# Generated by Django 5.0.6 on 2024-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default="No description available"),
            preserve_default=False,
        ),
    ]
